merge into MPA (mpa_id, mpa_name)
values (1, 'G'),
       (2, 'PG'),
       (3, 'PG13'),
       (4, 'R'),
       (5, 'NC17');

merge into genres (genre_id, genre_name)
values (1, 'COMEDY'),
       (2, 'DRAMA'),
       (3, 'CARTOON'),
       (4, 'THRILLER'),
       (5, 'DOCUMENTARY'),
       (6, 'ACTION'),
       (7, 'HORROR'),
       (8, 'FANTASY'),
       (9, 'FAMILY');


/*insert into MPA (mpa_id, mpa_name)
values (1, 'G'),
       (2, 'PG'),
       (3, 'PG13'),
       (4, 'R'),
       (5, 'NC17');*/

/*insert into MPA (mpa_name) -- если есть auto_increment или GENERATED BY DEFAULT в схеме
values ('G'),
       ('PG'),
       ('PG13'),
       ('R'),
       ('NC17');*/
